services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.10
